In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('C:/Users/Mulle/Desktop/Python-Dorset/Week 11/BTC-2020min.csv')
df

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,1609459140,2020-12-31 23:59:00,BTC/USD,28982.44,29024.59,28969.83,28992.79,5.897679,170990.182941
1,1609459080,2020-12-31 23:58:00,BTC/USD,29044.79,29048.62,29000.12,29000.12,20.362289,590508.837815
2,1609459020,2020-12-31 23:57:00,BTC/USD,29039.53,29048.63,29023.26,29044.79,14.503728,421257.721488
3,1609458960,2020-12-31 23:56:00,BTC/USD,29052.02,29059.42,29039.28,29039.53,2.707583,78626.925850
4,1609458900,2020-12-31 23:55:00,BTC/USD,29036.10,29052.02,29025.78,29052.02,7.631439,221708.705383
...,...,...,...,...,...,...,...,...,...
487717,1577837100,2020-01-01 00:05:00,BTC/USD,7156.52,7159.51,7150.10,7158.50,0.886932,6349.100145
487718,1577837040,2020-01-01 00:04:00,BTC/USD,7158.50,7158.50,7154.97,7157.20,0.971387,6952.408961
487719,1577836980,2020-01-01 00:03:00,BTC/USD,7158.82,7158.82,7156.90,7156.90,0.065819,471.062506
487720,1577836920,2020-01-01 00:02:00,BTC/USD,7158.82,7158.82,7158.82,7158.82,0.029278,209.595359
487721,1577836860,2020-01-01 00:01:00,BTC/USD,7161.51,7161.51,7155.09,7161.20,3.776924,27047.311443

1- Delete UNIX

In [8]:
df = df.drop(columns="unix")
df.head()

,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,2020-12-31 23:59:00,BTC/USD,28982.44,29024.59,28969.83,28992.79,5.897679,170990.182941
1,2020-12-31 23:58:00,BTC/USD,29044.79,29048.62,29000.12,29000.12,20.362289,590508.837815
2,2020-12-31 23:57:00,BTC/USD,29039.53,29048.63,29023.26,29044.79,14.503728,421257.721488
3,2020-12-31 23:56:00,BTC/USD,29052.02,29059.42,29039.28,29039.53,2.707583,78626.925850
4,2020-12-31 23:55:00,BTC/USD,29036.10,29052.02,29025.78,29052.02,7.631439,221708.705383

2- Make date as index

In [9]:
df.set_index("date")

,symbol,open,high,low,close,Volume BTC,Volume USD
date,,,,,,,
2020-12-31 23:59:00,BTC/USD,28982.44,29024.59,28969.83,28992.79,5.897679,170990.182941
2020-12-31 23:58:00,BTC/USD,29044.79,29048.62,29000.12,29000.12,20.362289,590508.837815
2020-12-31 23:57:00,BTC/USD,29039.53,29048.63,29023.26,29044.79,14.503728,421257.721488
2020-12-31 23:56:00,BTC/USD,29052.02,29059.42,29039.28,29039.53,2.707583,78626.925850
2020-12-31 23:55:00,BTC/USD,29036.10,29052.02,29025.78,29052.02,7.631439,221708.705383
...,...,...,...,...,...,...,...
2020-01-01 00:05:00,BTC/USD,7156.52,7159.51,7150.10,7158.50,0.886932,6349.100145
2020-01-01 00:04:00,BTC/USD,7158.50,7158.50,7154.97,7157.20,0.971387,6952.408961
2020-01-01 00:03:00,BTC/USD,7158.82,7158.82,7156.90,7156.90,0.065819,471.062506
2020-01-01 00:02:00,BTC/USD,7158.82,7158.82,7158.82,7158.82,0.029278,209.595359
2020-01-01 00:01:00,BTC/USD,7161.51,7161.51,7155.09,7161.20,3.776924,27047.311443

3- Make a single date dataframe

In [17]:
df['single date'] = df['date'].str.split(' ')[0]

ValueError: Length of values (2) does not match length of index (487722)